name: pyflextrkr
channels:
  - conda-forge
dependencies:
  - python==3.12.*
  - astropy
  - cartopy
  - colorcet
  - colormaps
  - colormath
  - dask
  - easygems
  - ffmpeg
  - healpix
  - intake==0.7.0
  - intake-xarray==0.7.0
  - ipython
  - joblib
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - pytz
  - scikit-image>=0.22
  - scikit-learn
  - scipy>=1.4
  - seaborn
  - xarray>=2025.1.2
  - xesmf>=0.8
  - zarr<3.0.0
